name: deploy-pto-detector
on:
  push:
    branches:
      - pto-detector
    paths:
      - 'pto_detector/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: qxf2/py-lambda-action@v1.0.2
      with:
        lambda_directory: 'pto_detector'
        lambda_function_name: 'arn:aws:lambda:ap-south-1:285993504765:function:pto_detector'
        lambda_layer_arn: 'arn:aws:lambda:ap-south-1:285993504765:layer:requests-boto'
        requirements_txt: 'pto_detector/requirements.txt'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.SKYPE_SENDER_REGION }}